import{a as v,S as w,i as c}from"./assets/vendor-DQvd0HNi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const b="55146791-665630d79c22972c7e4b14b80",S="https://pixabay.com/api/";async function y(a,t){const r={key:b,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await v.get(S,{params:r})).data}const g=document.querySelector(".gallery"),l=document.querySelector(".loader"),u=document.querySelector(".load-more"),q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function h(a){const t=a.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img 
            src="${r.webformatURL}" 
            alt="${r.tags}" 
            loading="lazy"
          />
        </a>
      </li>
    `).join("");g.insertAdjacentHTML("beforeend",t),q.refresh()}function M(){g.innerHTML=""}function p(){l&&l.classList.add("active")}function L(){l&&l.classList.remove("active")}function B(){u&&u.classList.add("active")}function f(){u&&u.classList.remove("active")}const P=document.querySelector(".form"),O=document.querySelector(".load-more");let i="",n=1,m=0;P.addEventListener("submit",async a=>{if(a.preventDefault(),i=a.target.elements.searchQuery.value.trim(),!!i){n=1,M(),f(),p();try{const t=await y(i,n);if(t.hits.length===0){c.error({message:"Sorry, no images found."});return}m=t.totalHits,h(t.hits),Math.ceil(m/15)>1?B():f()}catch{c.error({message:"Something went wrong."})}finally{L()}}});O.addEventListener("click",async()=>{n+=1,p();try{const a=await y(i,n);h(a.hits);const t=Math.ceil(m/15),r=document.querySelector(".gallery-item");if(r){const{height:s}=r.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}n>=t&&(f(),c.info({message:"We're sorry, but you've reached the end of search results."}))}catch{c.error({message:"Something went wrong."})}finally{L()}});
//# sourceMappingURL=index.js.map
