import{a as L,S,i as c}from"./assets/vendor-DQvd0HNi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const b="55146791-665630d79c22972c7e4b14b80",v="https://pixabay.com/api/";async function f(e,t){const a={key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await L.get(v,{params:a})).data}const w=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(e){const t=document.querySelector(".gallery"),a=e.map(n=>`
      <li class="gallery-item">
        <a href="${n.largeImageURL}">
          <img 
            src="${n.webformatURL}" 
            alt="${n.tags}" 
            loading="lazy"
          />
        </a>
      </li>
    `).join("");t.insertAdjacentHTML("beforeend",a),w.refresh()}function q(){const e=document.querySelector(".gallery");e.innerHTML=""}function m(){const e=document.querySelector(".loader");e&&e.classList.add("active")}function g(){const e=document.querySelector(".loader");e&&e.classList.remove("active")}function P(){const e=document.querySelector(".load-more");e&&e.classList.add("active")}function u(){const e=document.querySelector(".load-more");e&&e.classList.remove("active")}const d=document.querySelector(".form"),B=document.querySelector(".load-more");let i="",s=1,h=0;function p(){const e=Math.ceil(h/15);s>=e?(u(),c.info({message:"We're sorry, but you've reached the end of search results."})):P()}d.addEventListener("submit",async e=>{if(e.preventDefault(),i=e.target.elements.searchQuery.value.trim(),!!i){s=1,q(),u(),m();try{const t=await f(i,s);if(!t.hits||t.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}h=t.totalHits,y(t.hits),p(),d.reset()}catch{c.error({message:"Something went wrong. Please try again later."})}finally{g()}}});B.addEventListener("click",async()=>{s+=1,u(),m();try{const e=await f(i,s);if(e.hits&&e.hits.length>0){y(e.hits);const t=document.querySelectorAll(".gallery-item");if(t.length){const{height:a}=t[t.length-1].getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}}p()}catch{c.error({message:"Something went wrong. Please try again later."})}finally{g()}});
//# sourceMappingURL=index.js.map
